src/Entity/Artiest.php
<?php

namespace App\Entity;

use App\Repository\ArtiestRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArtiestRepository::class)]
class Artiest
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id;

    #[ORM\Column(length: 50)]
    private ?string $naam;

    #[ORM\Column(length: 50)]
    private ?string $genre = null;

    #[ORM\Column(length: 100)]
    private ?string $omschrijving = null;

    #[ORM\Column(length: 100)]
    private ?string $afbeelding_url = null;

    #[ORM\Column(length: 100)]
    private ?string $website = null;

    #[ORM\OneToMany(mappedBy: 'artiest', targetEntity: Optreden::class)]
    private $optredens;

    public function __construct()
    {
        $this->optredens = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNaam(): ?string
    {
        return $this->naam;
    }

    public function setNaam(string $naam): self
    {
        $this->naam = $naam;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getOmschrijving(): ?string
    {
        return $this->omschrijving;
    }

    public function setOmschrijving(string $omschrijving): self
    {
        $this->omschrijving = $omschrijving;

        return $this;
    }

    public function getAfbeeldingUrl(): ?string
    {
        return $this->afbeelding_url;
    }

    public function setAfbeeldingUrl(string $afbeelding_url): self
    {
        $this->afbeelding_url = $afbeelding_url;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(string $website): self
    {
        $this->website = $website;

        return $this;
    }

    /**
     * @return Collection<int, Optreden>
     */
    public function getOptredens(): Collection
    {
        return $this->optredens;
    }

    public function addOptreden(Optreden $optreden): self
    {
        if (!$this->optredens->contains($optreden)) {
            $this->optredens[] = $optreden;
            $optreden->setArtiest($this);
        }

        return $this;
    }

    public function removeOptreden(Optreden $optreden): self
    {
        if ($this->optredens->removeElement($optreden)) {
            // set the owning side to null (unless already changed)
            if ($optreden->getArtiest() === $this) {
                $optreden->setArtiest(null);
            }
        }

        return $this;
    }
}

src/Entity/Optreden.php
<?php

namespace App\Entity;

use App\Repository\OptredenRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OptredenRepository::class)]
class Optreden
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id;

    #[ORM\ManyToOne(inversedBy: 'optredens')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Poppodium $poppodium;

    #[ORM\ManyToOne(targetEntity: Artiest::class, inversedBy: 'optredens')]
    #[ORM\JoinColumn(nullable: false)]
    private $artiest;

    #[ORM\ManyToOne(targetEntity: Artiest::class, inversedBy: 'optredens')]
    #[ORM\JoinColumn(nullable: false)]
    private $voorprogramma;

    #[ORM\Column(length: 100)]
    private ?string $omschrijving = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $datum = null;

    #[ORM\Column]
    private ?int $prijs = null;

    #[ORM\Column(length: 100)]
    private ?string $ticket_url = null;

    #[ORM\Column(length: 100)]
    private ?string $afbeelding_url = null;

    public function __construct()
    {
        $this->artiest = new ArrayCollection();
        $this->voorprogramma = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPoppodium(): ?Poppodium
    {
        return $this->poppodium;
    }

    public function setPoppodium(?Poppodium $poppodium): self
    {
        $this->poppodium = $poppodium;

        return $this;
    }

    public function getArtiest(): ?Artiest
    {
        return $this->artiest;
    }

    public function setArtiest(?Artiest $artiest): self
    {
        $this->artiest = $artiest;

        return $this;
    }

    public function getVoorprogramma(): ?Artiest
    {
        return $this->voorprogramma;
    }

    public function setVoorprogramma(?Artiest $voorprogramma): self
    {
        $this->voorprogramma = $voorprogramma;

        return $this;
    }

    public function getOmschrijving(): ?string
    {
        return $this->omschrijving;
    }

    public function setOmschrijving(string $omschrijving): self
    {
        $this->omschrijving = $omschrijving;

        return $this;
    }

    public function getDatum(): ?\DateTimeInterface
    {
        return $this->datum;
    }

    public function setDatum(\DateTimeInterface $datum): self
    {
        $this->datum = $datum;

        return $this;
    }

    public function getPrijs(): ?int
    {
        return $this->prijs;
    }

    public function setPrijs(int $prijs): self
    {
        $this->prijs = $prijs;

        return $this;
    }

    public function getTicketUrl(): ?string
    {
        return $this->ticket_url;
    }

    public function setTicketUrl(string $ticket_url): self
    {
        $this->ticket_url = $ticket_url;

        return $this;
    }

    public function getAfbeeldingUrl(): ?string
    {
        return $this->afbeelding_url;
    }

    public function setAfbeeldingUrl(string $afbeelding_url): self
    {
        $this->afbeelding_url = $afbeelding_url;

        return $this;
    }
}

src/Controller/HomepageController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Response;
//use Symfony\Component\HttpFoundation\RedirectResponse;
//use Symfony\Component\HttpFoundation\Request;

use App\Entity\Optreden;

#[Route('/')]
class HomepageController extends AbstractController
{
    #[Route('/', name: 'homepage')]
    public function index()
    {
        $rep = $this->getDoctrine()->getRepository(Optreden::class);
        $data = $rep->getAllOptredens();

        dump($data);
        die();
    }

}
    /*
    #[Route('/', name: 'homepage')]
    #[Template()]
    public function index() {
        return ['controller_name' => 'HomepageController'];
    }

    #[Route('/backhome', name: 'backhome')]
    public function backhome() {
        return $this->redirectToRoute('homepage');
    }

    // meertaligheid
    #[Route(path: [
        'en' => '/contact-us',
        'nl' => '/neem-contact-op'
    ], name: 'contact')]
    public function contact(Request $request) {
        $locale = $request->getLocale();
        $msg = "This page is in English";
        if($locale == "nl") {
            $msg = "Deze pagina is in het Nederlands";
        }
        return new Response(
            "<html><body>$msg</body></html>"
        );
    }

    // json en xml response
    #[Route('/data.{_format}', name: 'api_output', requirements: ['format' => 'xml|json'])]
    public function api($_format) {
        $data = [
            ["id" => 1, "naam" => "Piet"],
            ["id" => 2, "naam" => "Wilma"],
            ["id" => 3, "naam" => "Harry"]
        ];

        if ($_format == 'json') {
            return($this->json($data));
        } else {                                // om een array naar XML om te zetten is een parser nodig.
            $d = "<data>";                      // hier even een snelle oplossing --> kan eventueel ook met Twig
                foreach ($data as $record) {
                    $id = $record['id'];
                    $naam = $record['naam'];
                    $d .= "<record id='$id'>$naam</record>";
                }
            $d .= "<data>";
            return(new Response($d));    
        }
    }
    
    //request
    #[Route('/save-data', name:'homepage_save_data')] 
    public function saveData(Request $request) {
        //$params = $request->request->all();
        $params = $request->get('input');
        dd($params);
    }
} */

templates/homepage/homepage.json.twig
{% block body %}

    {% for optreden in optredens %}
        {"optreden": [ 
            {
                "poppodium": {{optreden.Poppodium.Naam}},
                "hoofdprogramma": {{optreden.Artiest.Naam}},
                "voorprogramma": {{optreden.Voorprogramma.Naam}},
                "omschrijving": {{optreden.omschrijving}},
                "datum": {{optreden.Datum|date('y-m-d H:i')}},
                "prijs": {{optreden.Prijs }},
                "ticket": {{optreden.TicketUrl}},
                "afbeelding": {{optreden.AfbeeldingUrl}},
            }
        ]}

    {% endfor %}

{% endblock %}

templates/homepage/homepage.xml.twig
<?xml version="1.0" encoding="UTF-8"?>

<data>
{% block body %}

    <optredens>
        {% for record in data  %}
            <id> {{record.id}} </id>
            <poppodium> {{record.poppodium.id}} </poppodium>
            <artiest> {{record.artiest.id}} </artiest>
            <voorprogramma> {{record.voorprogramma.id}} </voorprogramma> 
            <omschrijving> {{record.omschrijving}} </omschrijving>
            <datum> {{record.datum|date('d-m-Y')}} </datum>
            <prijs> {{record.prijs}} </prijs>  
            <ticket> {{record.ticketUrl}} </ticket>
            <afbeelding> {{record.afbeeldingUrl}} </afbeelding>
        {% endfor %}

    </optredens>

{% endblock %}
</data>

templates/homepage/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomepageController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/educom-symfony/src/Controller/HomepageController.php'|file_link(0) }}">src/Controller/HomepageController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/educom-symfony/templates/homepage/index.html.twig'|file_link(0) }}">templates/homepage/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}